apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: charts
  name: charts
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: charts
    spec:
      containers:
      - image: kisa7/musicplayer:charts
        name: charts
        resources: {}
      restartPolicy: Always
status: {}
